# Generated by Django 4.2.13 on 2026-06-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Oddiy'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('likes_per_day', models.IntegerField(default=20)),
                ('super_likes_per_day', models.IntegerField(default=0)),
                ('can_see_who_liked', models.BooleanField(default=False)),
                ('can_use_radius_filter', models.BooleanField(default=False)),
                ('can_send_voice', models.BooleanField(default=False)),
                ('can_send_video_msg', models.BooleanField(default=False)),
                ('can_boost_profile', models.BooleanField(default=False)),
                ('can_see_story_analytics', models.BooleanField(default=False)),
                ('stories_per_day', models.IntegerField(default=1)),
                ('ad_free', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
        ),
    ]
