# Generated by Django 4.2.13 on 2026-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_seed_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name_uz', 'name'], 'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name_uz', 'name'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
