# Generated by Django 4.2.13 on 2026-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
